# Generated by Django 2.2 on 2019-05-04 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_auto_20190502_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('id', 'Indonesian')], default='en-us', max_length=6, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='post.Category', verbose_name='Parent Category'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('description', models.CharField(max_length=158, verbose_name='Description')),
                ('slug', models.CharField(blank=True, db_index=True, max_length=128, unique=True, verbose_name='Slug')),
                ('body', models.TextField(verbose_name='Body')),
                ('body_preview', models.TextField(verbose_name='Body Preview')),
                ('read', models.IntegerField(default=0, verbose_name='Read')),
                ('state', models.IntegerField(default=0, verbose_name='State')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Publish Date')),
                ('language', models.CharField(choices=[('en-us', 'English'), ('id', 'Indonesian')], default='en-us', max_length=6, verbose_name='Language')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='post.Category', verbose_name='Category')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'db_table': 'djwb_post',
                'ordering': ['-publish_date'],
            },
        ),
    ]
